[package]
name = "rust_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
serde = "1.0"
polars = "0.33.2"
csv = "1.3.0"
anyhow = "1.0.75"
env = "0.0.0"
io = "0.0.2"
serde_derive = "1.0.189"
