name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: make install
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: format
        run: make format
      # - name: deploy
      #   run: make deploy
       # Set up Rust environment
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
         toolchain: stable
         override: true
